-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.campaign DROP CONSTRAINT IF EXISTS fk_campaign_category_id;

ALTER TABLE IF EXISTS public.campaign DROP CONSTRAINT IF EXISTS fk_campaign_contact_id;

ALTER TABLE IF EXISTS public.campaign DROP CONSTRAINT IF EXISTS fk_campaign_subcategory_id;



DROP TABLE IF EXISTS public.campaign;

CREATE TABLE IF NOT EXISTS public.campaign
(
    cf_id character varying(4) COLLATE pg_catalog."default" NOT NULL,
    contact_id character varying(4) COLLATE pg_catalog."default" NOT NULL,
    company_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    goal integer NOT NULL,
    pledged integer NOT NULL,
    outcome character varying(25) COLLATE pg_catalog."default" NOT NULL,
    backers_count integer NOT NULL,
    country character varying(2) COLLATE pg_catalog."default" NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL,
    launched_date date NOT NULL,
    end_date date NOT NULL,
    staff_pick character varying(10) COLLATE pg_catalog."default" NOT NULL,
    spotlight character varying(10) COLLATE pg_catalog."default" NOT NULL,
    category_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    subcategory_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    last_updated timestamp without time zone NOT NULL,
    CONSTRAINT pk_campaign PRIMARY KEY (cf_id)
);

DROP TABLE IF EXISTS public.category;

CREATE TABLE IF NOT EXISTS public.category
(
    category_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_updated timestamp without time zone NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

DROP TABLE IF EXISTS public.contacts;

CREATE TABLE IF NOT EXISTS public.contacts
(
    contact_id character varying(4) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_updated timestamp without time zone NOT NULL,
    CONSTRAINT pk_contacts PRIMARY KEY (contact_id)
);

DROP TABLE IF EXISTS public.subcategory;

CREATE TABLE IF NOT EXISTS public.subcategory
(
    subcategory_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    subcategory character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_updated timestamp without time zone NOT NULL,
    CONSTRAINT pk_subcategory PRIMARY KEY (subcategory_id)
);

ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT fk_campaign_category_id FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT fk_campaign_contact_id FOREIGN KEY (contact_id)
    REFERENCES public.contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT fk_campaign_subcategory_id FOREIGN KEY (subcategory_id)
    REFERENCES public.subcategory (subcategory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;